### ISSUE TITLE
Struggling to connect to 

### ISSUE THREAD

**Issue by Dave592309** [google-coral/project-cloud-monitor#6]
When running the first step in setting up 'inference on Edge' i'm running into an issue - see below.

W: Failed to fetch https://packages.cloud.google.com/apt/dists/coral-edgetpu-stable/InRelease  Cannot initiate the connection to packages.cloud.google.com:443 (2404:6800:4006:810::200e). - connect (101: Network is unreachable)

Maybe I need to add my key from Google Console? the -key add - section? If that is the case - where do I get this key? And do I delete the - -? 

Thanks

-------->

echo "deb https://packages.cloud.google.com/apt coral-cloud-stable main" | sudo tee /etc/apt/sources.list.d/coral-cloud.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

sudo apt update

sudo apt install python3-coral-cloudiot

**Comment by manoj7410** [comment]
Looks like some network issue at your end. Here are the detailed logs from my DevBoard (The commands have been highlighted):

**mendel@yellow-rabbit:~$ sudo apt update**
Get:1 file:/var/cache/mdt/packages ./ InRelease
Ign:1 file:/var/cache/mdt/packages ./ InRelease
Get:2 file:/var/cache/mdt/packages ./ Release
Ign:2 file:/var/cache/mdt/packages ./ Release
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Get:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Hit:6 https://deb.debian.org/debian-security buster/updates InRelease          
Hit:7 https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease    
Hit:8 https://mendel-linux.org/apt/eagle-bsp-enterprise eagle InRelease        
Hit:9 https://mendel-linux.org/apt/eagle eagle InRelease
Reading package lists... Done
Building dependency tree      
Reading state information... Done
33 packages can be upgraded. Run 'apt list --upgradable' to see them.
**mendel@yellow-rabbit:~$ sudo apt dist-upgrade**
Reading package lists... Done
Building dependency tree      
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  freeglut3 gstreamer1.0-plugins-ugly gstreamer1.0-python3-plugin-loader
  liba52-0.7.4 libcdio18 libmpeg2-4 libopencore-amrnb0 libopencore-amrwb0
  libsidplay1v5 python3-opengl
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  edgetpudemo enterprise-core enterprise-gui libedgetpu1-std python3-edgetpu
  python3-edgetpuvision
The following NEW packages will be installed:
  imx-gpu-viv-ko
The following packages will be upgraded:
  apt apt-transport-https apt-utils imx-board-tools imx-gpu-viv krb5-locales
  libapt-inst2.0 libapt-pkg5.0 libexif12 libfreetype6 libgssapi-krb5-2
  libk5crypto3 libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common
  libmariadb3 libproxy1v5 libssl1.1 linux-libc-dev mariadb-common
  mendel-minimal openssl python-apt-common python3-apt usb-gadget
  xserver-common xwayland
28 upgraded, 1 newly installed, 6 to remove and 0 not upgraded.
Need to get 17.9 MB of archives.
After this operation, 79.4 MB disk space will be freed.
Do you want to continue? [Y/n] Y
Get:1 https://deb.debian.org/debian-security buster/updates/main arm64 libapt-pkg5.0 arm64 1.8.2.2 [897 kB]
Get:2 https://deb.debian.org/debian-security buster/updates/main arm64 libapt-inst2.0 arm64 1.8.2.2 [202 kB]
Get:3 https://deb.debian.org/debian-security buster/updates/main arm64 apt arm64 1.8.2.2 [1,370 kB]
Get:4 https://deb.debian.org/debian-security buster/updates/main arm64 apt-utils arm64 1.8.2.2 [411 kB]
Get:5 https://deb.debian.org/debian-security buster/updates/main arm64 libssl1.1 arm64 1.1.1d-0+deb10u4 [1,382 kB]
Get:6 https://deb.debian.org/debian-security buster/updates/main arm64 krb5-locales all 1.17-3+deb10u1 [95.4 kB]
Get:7 https://deb.debian.org/debian-security buster/updates/main arm64 libgssapi-krb5-2 arm64 1.17-3+deb10u1 [150 kB]
Get:8 https://mendel-linux.org/apt/eagle-bsp-enterprise eagle/main arm64 imx-board-tools all 6-3 [6,564 B]
Get:9 https://mendel-linux.org/apt/eagle-bsp-enterprise eagle/main arm64 imx-gpu-viv arm64 6.4.2-2 [3,580 kB]
Get:10 https://deb.debian.org/debian-security buster/updates/main arm64 libkrb5-3 arm64 1.17-3+deb10u1 [351 kB]
Get:11 https://deb.debian.org/debian-security buster/updates/main arm64 libkrb5support0 arm64 1.17-3+deb10u1 [64.9 kB]
Get:12 https://deb.debian.org/debian-security buster/updates/main arm64 libk5crypto3 arm64 1.17-3+deb10u1 [123 kB]
Get:13 https://deb.debian.org/debian-security buster/updates/main arm64 libldap-common all 2.4.47+dfsg-3+deb10u4 [89.8 kB]
Get:14 https://deb.debian.org/debian-security buster/updates/main arm64 libldap-2.4-2 arm64 2.4.47+dfsg-3+deb10u4 [216 kB]
Get:15 https://deb.debian.org/debian-security buster/updates/main arm64 apt-transport-https all 1.8.2.2 [149 kB]
Get:16 https://deb.debian.org/debian-security buster/updates/main arm64 libexif12 arm64 0.6.21-5.1+deb10u5 [322 kB]
Get:17 https://deb.debian.org/debian-security buster/updates/main arm64 libfreetype6 arm64 2.9.1-3+deb10u2 [355 kB]
Get:18 https://deb.debian.org/debian-security buster/updates/main arm64 mariadb-common all 1:10.3.25-0+deb10u1 [32.1 kB]
Get:19 https://deb.debian.org/debian-security buster/updates/main arm64 libmariadb3 arm64 1:10.3.25-0+deb10u1 [161 kB]
Get:20 https://deb.debian.org/debian-security buster/updates/main arm64 libproxy1v5 arm64 0.4.15-5+deb10u1 [52.3 kB]
Get:21 https://deb.debian.org/debian-security buster/updates/main arm64 linux-libc-dev arm64 4.19.152-1 [1,382 kB]
Get:22 https://deb.debian.org/debian-security buster/updates/main arm64 openssl arm64 1.1.1d-0+deb10u4 [823 kB]
Get:23 https://deb.debian.org/debian-security buster/updates/main arm64 python-apt-common all 1.8.4.2 [96.2 kB]
Get:24 https://deb.debian.org/debian-security buster/updates/main arm64 python3-apt arm64 1.8.4.2 [179 kB]
Get:25 https://deb.debian.org/debian-security buster/updates/main arm64 xserver-common all 2:1.20.4-1+deb10u2 [2,235 kB]
Get:26 https://mendel-linux.org/apt/eagle-bsp-enterprise eagle/main arm64 imx-gpu-viv-ko arm64 6.4.2-2 [141 kB]
Get:27 https://deb.debian.org/debian-security buster/updates/main arm64 xwayland arm64 2:1.20.4-1+deb10u2 [3,011 kB]
Get:28 https://mendel-linux.org/apt/eagle eagle/main arm64 mendel-minimal all 8-4 [5,544 B]
Get:29 https://mendel-linux.org/apt/eagle eagle/main arm64 usb-gadget all 3-2 [5,800 B]
Fetched 17.9 MB in 10s (1,874 kB/s)                                            
Reading changelogs... Done
Preconfiguring packages ...
(Reading database ... 50652 files and directories currently installed.)
Preparing to unpack .../libapt-pkg5.0_1.8.2.2_arm64.deb ...
Unpacking libapt-pkg5.0:arm64 (1.8.2.2) over (1.8.2.1) ...
Setting up libapt-pkg5.0:arm64 (1.8.2.2) ...
(Reading database ... 50652 files and directories currently installed.)
Preparing to unpack .../libapt-inst2.0_1.8.2.2_arm64.deb ...
Unpacking libapt-inst2.0:arm64 (1.8.2.2) over (1.8.2.1) ...
Preparing to unpack .../archives/apt_1.8.2.2_arm64.deb ...
Unpacking apt (1.8.2.2) over (1.8.2.1) ...
Setting up apt (1.8.2.2) ...
(Reading database ... 50652 files and directories currently installed.)
Preparing to unpack .../apt-utils_1.8.2.2_arm64.deb ...
Unpacking apt-utils (1.8.2.2) over (1.8.2.1) ...
(Reading database ... 50652 files and directories currently installed.)
Removing enterprise-gui (2-1) ...
Removing enterprise-core (2-1) ...
Removing edgetpudemo (3-1) ...
Removing python3-edgetpuvision (6-1) ...
Removing python3-edgetpu (14.1) ...
Removing libedgetpu1-std:arm64 (14.1) ...
(Reading database ... 50536 files and directories currently installed.)
Preparing to unpack .../00-libssl1.1_1.1.1d-0+deb10u4_arm64.deb ...
Unpacking libssl1.1:arm64 (1.1.1d-0+deb10u4) over (1.1.1d-0+deb10u3) ...
Preparing to unpack .../01-krb5-locales_1.17-3+deb10u1_all.deb ...
Unpacking krb5-locales (1.17-3+deb10u1) over (1.17-3) ...
Preparing to unpack .../02-libgssapi-krb5-2_1.17-3+deb10u1_arm64.deb ...
Unpacking libgssapi-krb5-2:arm64 (1.17-3+deb10u1) over (1.17-3) ...
Preparing to unpack .../03-libkrb5-3_1.17-3+deb10u1_arm64.deb ...
Unpacking libkrb5-3:arm64 (1.17-3+deb10u1) over (1.17-3) ...
Preparing to unpack .../04-libkrb5support0_1.17-3+deb10u1_arm64.deb ...
Unpacking libkrb5support0:arm64 (1.17-3+deb10u1) over (1.17-3) ...
Preparing to unpack .../05-libk5crypto3_1.17-3+deb10u1_arm64.deb ...
Unpacking libk5crypto3:arm64 (1.17-3+deb10u1) over (1.17-3) ...
Preparing to unpack .../06-libldap-common_2.4.47+dfsg-3+deb10u4_all.deb ...
Unpacking libldap-common (2.4.47+dfsg-3+deb10u4) over (2.4.47+dfsg-3+deb10u2) ...
Preparing to unpack .../07-libldap-2.4-2_2.4.47+dfsg-3+deb10u4_arm64.deb ...
Unpacking libldap-2.4-2:arm64 (2.4.47+dfsg-3+deb10u4) over (2.4.47+dfsg-3+deb10u2) ...
Preparing to unpack .../08-apt-transport-https_1.8.2.2_all.deb ...
Unpacking apt-transport-https (1.8.2.2) over (1.8.2.1) ...
Preparing to unpack .../09-imx-board-tools_6-3_all.deb ...
Unpacking imx-board-tools (6-3) over (6-2) ...
Preparing to unpack .../10-imx-gpu-viv_6.4.2-2_arm64.deb ...
Unpacking imx-gpu-viv (6.4.2-2) over (6.4.2-1) ...
Selecting previously unselected package imx-gpu-viv-ko.
Preparing to unpack .../11-imx-gpu-viv-ko_6.4.2-2_arm64.deb ...
Unpacking imx-gpu-viv-ko (6.4.2-2) ...
Preparing to unpack .../12-libexif12_0.6.21-5.1+deb10u5_arm64.deb ...
Unpacking libexif12:arm64 (0.6.21-5.1+deb10u5) over (0.6.21-5.1+deb10u1) ...
Preparing to unpack .../13-libfreetype6_2.9.1-3+deb10u2_arm64.deb ...
Unpacking libfreetype6:arm64 (2.9.1-3+deb10u2) over (2.9.1-3+deb10u1) ...
Preparing to unpack .../14-mariadb-common_1%3a10.3.25-0+deb10u1_all.deb ...
Unpacking mariadb-common (1:10.3.25-0+deb10u1) over (1:10.3.22-0+deb10u1) ...
Preparing to unpack .../15-libmariadb3_1%3a10.3.25-0+deb10u1_arm64.deb ...
Unpacking libmariadb3:arm64 (1:10.3.25-0+deb10u1) over (1:10.3.22-0+deb10u1) ...
Preparing to unpack .../16-libproxy1v5_0.4.15-5+deb10u1_arm64.deb ...
Unpacking libproxy1v5:arm64 (0.4.15-5+deb10u1) over (0.4.15-5) ...
Preparing to unpack .../17-linux-libc-dev_4.19.152-1_arm64.deb ...
Unpacking linux-libc-dev:arm64 (4.19.152-1) over (4.19.118-2+deb10u1) ...
Preparing to unpack .../18-mendel-minimal_8-4_all.deb ...
Unpacking mendel-minimal (8-4) over (8-3) ...
Preparing to unpack .../19-openssl_1.1.1d-0+deb10u4_arm64.deb ...
Unpacking openssl (1.1.1d-0+deb10u4) over (1.1.1d-0+deb10u3) ...
Preparing to unpack .../20-python-apt-common_1.8.4.2_all.deb ...
Unpacking python-apt-common (1.8.4.2) over (1.8.4.1) ...
Preparing to unpack .../21-python3-apt_1.8.4.2_arm64.deb ...
Unpacking python3-apt (1.8.4.2) over (1.8.4.1) ...
Preparing to unpack .../22-usb-gadget_3-2_all.deb ...
Unpacking usb-gadget (3-2) over (3-1) ...
Preparing to unpack .../23-xserver-common_2%3a1.20.4-1+deb10u2_all.deb ...
Unpacking xserver-common (2:1.20.4-1+deb10u2) over (2:1.20.4-1+deb10u1) ...
Preparing to unpack .../24-xwayland_2%3a1.20.4-1+deb10u2_arm64.deb ...
Unpacking xwayland (2:1.20.4-1+deb10u2) over (2:1.20.4-1+deb10u1) ...
Setting up usb-gadget (3-2) ...
Setting up libproxy1v5:arm64 (0.4.15-5+deb10u1) ...
Setting up apt-transport-https (1.8.2.2) ...
Setting up imx-board-tools (6-3) ...
Setting up libssl1.1:arm64 (1.1.1d-0+deb10u4) ...
Setting up linux-libc-dev:arm64 (4.19.152-1) ...
Setting up krb5-locales (1.17-3+deb10u1) ...
Setting up libapt-inst2.0:arm64 (1.8.2.2) ...
Setting up libldap-common (2.4.47+dfsg-3+deb10u4) ...
Setting up libkrb5support0:arm64 (1.17-3+deb10u1) ...
Setting up mariadb-common (1:10.3.25-0+deb10u1) ...
Setting up libfreetype6:arm64 (2.9.1-3+deb10u2) ...
Setting up imx-gpu-viv-ko (6.4.2-2) ...
Setting up libexif12:arm64 (0.6.21-5.1+deb10u5) ...
Setting up libmariadb3:arm64 (1:10.3.25-0+deb10u1) ...
Setting up libk5crypto3:arm64 (1.17-3+deb10u1) ...
Setting up python-apt-common (1.8.4.2) ...
Setting up libkrb5-3:arm64 (1.17-3+deb10u1) ...
Setting up xserver-common (2:1.20.4-1+deb10u2) ...
Setting up xwayland (2:1.20.4-1+deb10u2) ...
Setting up mendel-minimal (8-4) ...
Setting up openssl (1.1.1d-0+deb10u4) ...
Setting up apt-utils (1.8.2.2) ...
Setting up python3-apt (1.8.4.2) ...
Setting up imx-gpu-viv (6.4.2-2) ...
Setting up libldap-2.4-2:arm64 (2.4.47+dfsg-3+deb10u4) ...
Setting up libgssapi-krb5-2:arm64 (1.17-3+deb10u1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
**mendel@yellow-rabbit:~$ echo "deb https://packages.cloud.google.com/apt coral-cloud-stable main" | sudo tee /etc/apt/sources.list.d/coral-cloud.list**
deb https://packages.cloud.google.com/apt coral-cloud-stable main
mendel@yellow-rabbit:~$
mendel@yellow-rabbit:~$
mendel@yellow-rabbit:~$
mendel@yellow-rabbit:~$
**mendel@yellow-rabbit:~$ curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1974  100  1974    0     0    369      0  0:00:05  0:00:05 --:--:--   508
OK
mendel@yellow-rabbit:~$
**mendel@yellow-rabbit:~$ sudo apt update**
Get:1 file:/var/cache/mdt/packages ./ InRelease
Ign:1 file:/var/cache/mdt/packages ./ InRelease
Get:2 file:/var/cache/mdt/packages ./ Release
Ign:2 file:/var/cache/mdt/packages ./ Release
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:4 file:/var/cache/mdt/packages ./ Translation-en_US
Get:5 file:/var/cache/mdt/packages ./ Translation-en
Ign:5 file:/var/cache/mdt/packages ./ Translation-en
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:4 file:/var/cache/mdt/packages ./ Translation-en_US
Get:5 file:/var/cache/mdt/packages ./ Translation-en
Ign:5 file:/var/cache/mdt/packages ./ Translation-en
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:4 file:/var/cache/mdt/packages ./ Translation-en_US
Get:5 file:/var/cache/mdt/packages ./ Translation-en
Ign:5 file:/var/cache/mdt/packages ./ Translation-en
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:4 file:/var/cache/mdt/packages ./ Translation-en_US
Get:5 file:/var/cache/mdt/packages ./ Translation-en
Ign:5 file:/var/cache/mdt/packages ./ Translation-en
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:4 file:/var/cache/mdt/packages ./ Translation-en_US
Get:5 file:/var/cache/mdt/packages ./ Translation-en
Ign:5 file:/var/cache/mdt/packages ./ Translation-en
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:4 file:/var/cache/mdt/packages ./ Translation-en_US
Get:5 file:/var/cache/mdt/packages ./ Translation-en
Ign:5 file:/var/cache/mdt/packages ./ Translation-en
Get:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:4 file:/var/cache/mdt/packages ./ Translation-en_US
Get:5 file:/var/cache/mdt/packages ./ Translation-en
Ign:5 file:/var/cache/mdt/packages ./ Translation-en
Hit:6 https://deb.debian.org/debian-security buster/updates InRelease
Hit:7 https://mendel-linux.org/apt/eagle-bsp-enterprise eagle InRelease
Hit:8 https://mendel-linux.org/apt/eagle eagle InRelease
Get:9 https://packages.cloud.google.com/apt coral-cloud-stable InRelease [6,718 B]
Hit:10 https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease
Ign:11 https://packages.cloud.google.com/apt coral-cloud-stable/main arm64 Packages
Get:11 https://packages.cloud.google.com/apt coral-cloud-stable/main arm64 Packages [3,685 B]
Fetched 10.4 kB in 8s (1,293 B/s)    
Reading package lists... Done
Building dependency tree      
Reading state information... Done
All packages are up to date.
**mendel@yellow-rabbit:~$ sudo apt install python3-coral-cloudiot**
Reading package lists... Done
Building dependency tree      
Reading state information... Done
The following packages were automatically installed and are no longer required:
  freeglut3 gstreamer1.0-plugins-ugly gstreamer1.0-python3-plugin-loader
  liba52-0.7.4 libcdio18 libmpeg2-4 libopencore-amrnb0 libopencore-amrwb0
  libsidplay1v5 python3-opengl
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-asn1crypto python3-cffi-backend python3-cryptoauthlib
  python3-cryptography python3-paho-mqtt
Suggested packages:
  python-cryptography-doc python3-cryptography-vectors
The following NEW packages will be installed:
  python3-asn1crypto python3-cffi-backend python3-coral-cloudiot
  python3-cryptoauthlib python3-cryptography python3-paho-mqtt
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 478 kB of archives.
After this operation, 2,931 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://packages.cloud.google.com/apt coral-cloud-stable/main arm64 python3-cryptoauthlib arm64 20190304-3 [66.3 kB]
Get:2 https://packages.cloud.google.com/apt coral-cloud-stable/main arm64 python3-coral-cloudiot all 1.2 [6,816 B]
Get:3 https://mendel-linux.org/apt/eagle eagle/main arm64 python3-asn1crypto all 0.24.0-1 [78.2 kB]
Get:4 https://mendel-linux.org/apt/eagle eagle/main arm64 python3-cffi-backend arm64 1.12.2-1 [80.5 kB]
Get:5 https://mendel-linux.org/apt/eagle eagle/main arm64 python3-paho-mqtt all 1.4.0-1 [44.9 kB]
Get:6 https://mendel-linux.org/apt/eagle eagle/main arm64 python3-cryptography arm64 2.6.1-3+deb10u2 [201 kB]
Fetched 478 kB in 8s (62.8 kB/s)                                              
Selecting previously unselected package python3-asn1crypto.
(Reading database ... 50539 files and directories currently installed.)
Preparing to unpack .../0-python3-asn1crypto_0.24.0-1_all.deb ...
Unpacking python3-asn1crypto (0.24.0-1) ...
Selecting previously unselected package python3-cffi-backend.
Preparing to unpack .../1-python3-cffi-backend_1.12.2-1_arm64.deb ...
Unpacking python3-cffi-backend (1.12.2-1) ...
Selecting previously unselected package python3-paho-mqtt.
Preparing to unpack .../2-python3-paho-mqtt_1.4.0-1_all.deb ...
Unpacking python3-paho-mqtt (1.4.0-1) ...
Selecting previously unselected package python3-cryptoauthlib.
Preparing to unpack .../3-python3-cryptoauthlib_20190304-3_arm64.deb ...
Unpacking python3-cryptoauthlib (20190304-3) ...
Selecting previously unselected package python3-cryptography.
Preparing to unpack .../4-python3-cryptography_2.6.1-3+deb10u2_arm64.deb ...
Unpacking python3-cryptography (2.6.1-3+deb10u2) ...
Selecting previously unselected package python3-coral-cloudiot.
Preparing to unpack .../5-python3-coral-cloudiot_1.2_all.deb ...
Unpacking python3-coral-cloudiot (1.2) ...
Setting up python3-paho-mqtt (1.4.0-1) ...
Setting up python3-asn1crypto (0.24.0-1) ...
Setting up python3-cffi-backend (1.12.2-1) ...
Setting up python3-cryptoauthlib (20190304-3) ...
Setting up python3-cryptography (2.6.1-3+deb10u2) ...
Setting up python3-coral-cloudiot (1.2) ...
mendel@yellow-rabbit:~$

**Comment by Dave592309** [comment]
**I ran this first:**
sudo apt dist-upgrade

**Then I ran:**
`echo "deb https://packages.cloud.google.com/apt coral-cloud-stable main" | sudo tee /etc/apt/sources.list.d/coral-cloud.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

sudo apt update

sudo apt install python3-coral-cloudiot`


**This is the logs I got from it:**
`Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US
Get:3 file:/var/cache/mdt/packages ./ Packages
Ign:3 file:/var/cache/mdt/packages ./ Packages
Get:4 file:/var/cache/mdt/packages ./ Translation-en
Ign:4 file:/var/cache/mdt/packages ./ Translation-en
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US                        
Get:3 file:/var/cache/mdt/packages ./ Packages                                 
Get:4 file:/var/cache/mdt/packages ./ Translation-en                           
Ign:4 file:/var/cache/mdt/packages ./ Translation-en                           
Get:5 file:/var/cache/mdt/packages ./ Translation-en_US                        
Ign:5 file:/var/cache/mdt/packages ./ Translation-en_US                        
Err:6 https://packages.cloud.google.com/apt coral-cloud-stable InRelease       
  Cannot initiate the connection to packages.cloud.google.com:443 (2404:6800:4006:805::200e). - connect (101: Network is unreachable) Could not connect to packages.cloud.google.com:443 (216.58.203.110), connection timed out
Err:7 https://packages.cloud.google.com/apt mendel-bsp-enterprise-day InRelease
  Cannot initiate the connection to packages.cloud.google.com:443 (2404:6800:4006:805::200e). - connect (101: Network is unreachable)
Err:8 https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease
  Cannot initiate the connection to packages.cloud.google.com:443 (2404:6800:4006:805::200e). - connect (101: Network is unreachable)
Err:9 https://packages.cloud.google.com/apt mendel-day InRelease
  Cannot initiate the connection to packages.cloud.google.com:443 (2404:6800:4006:805::200e). - connect (101: Network is unreachable)
Reading package lists... Done                                
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://packages.cloud.google.com/apt/dists/coral-cloud-stable/InRelease  Cannot initiate the connection to packages.cloud.google.com:443 (2404:6800:4006:805::200e). - connect (101: Network is unreachable) Could not connect to packages.cloud.google.com:443 (216.58.203.110), connection timed out
W: Failed to fetch https://packages.cloud.google.com/apt/dists/mendel-bsp-enterprise-day/InRelease  Cannot initiate the connection to packages.cloud.google.com:443 (2404:6800:4006:805::200e). - connect (101: Network is unreachable)
W: Failed to fetch https://packages.cloud.google.com/apt/dists/coral-edgetpu-stable/InRelease  Cannot initiate the connection to packages.cloud.google.com:443 (2404:6800:4006:805::200e). - connect (101: Network is unreachable)
W: Failed to fetch https://packages.cloud.google.com/apt/dists/mendel-day/InRelease  Cannot initiate the connection to packages.cloud.google.com:443 (2404:6800:4006:805::200e). - connect (101: Network is unreachable)
W: Some index files failed to download. They have been ignored, or old ones used instead.            
`

Any help or thoughts on it? I can't connect my current wifi connection to my board properly as i'm staying in a hotel. Could that be the problem?

**Comment by Dave592309** [comment]
Also tried running Step 2 and had issues..

`mendel@queen-llama:~$ git clone https://github.com/google-coral/project-cloud-monitor
Cloning into 'project-cloud-monitor'...
fatal: unable to access 'https://github.com/google-coral/project-cloud-monitor/': Failed to connect to github.com port 443: Connection timed out
`

**Comment by manoj7410** [comment]
@Dave592309 can you try to create a mobile hotspot and then try? Maybe the hotel network is restricted ?

**Comment by manoj7410** [comment]
Feel free to reopen if the issue still persists.
